name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: wizscreen-windows
        path: ./dist/windows

    - uses: actions/upload-artifact@v2
      with:
        name: wizscreen-linux
        path: ./dist/linux
